path: /Users/vincewang/YOLO_Project/config
train: /Users/vincewang/YOLO_Project/dataset/MBB_gray_processed/images/train
val: /Users/vincewang/YOLO_Project/dataset/MBB_gray_processed/images/val
names:
  0: '0'
  1: '1'
  2: '2'
  3: '3'
  4: '4'
  5: '5'
  6: '6'
  7: '7'
  8: '8'
  9: '9'
nc: 10
